In [1]:
import numpy as np

In [2]:
# consider array to be like a function that returns a data structure in the NumPy array format
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
# note the structure of the array that has been created
# 2 acknowledges there are 2 bracket series, also known as lists
# 4 refers to number of elements within each list, starting at zero
a.shape

(2, 4)

In [4]:
# Remembering to start counting at zero,
# This index query will produce the third element of the second list, which is 7 
a[1,3]

7

In [6]:
# we can also change the elements within a list of the array:
# for exmample, let's replace the number 5 with the number 8
a [1,1] = 8
a

array([[0, 1, 2, 3],
       [4, 8, 6, 7]])

In [7]:
# reference the array
a[0]

array([0, 1, 2, 3])

In [8]:
a[1]

array([4, 8, 6, 7])

In [9]:
# assign a new variable to a new array
b = np.array([3,5])
b

array([3, 5])

In [11]:
# use .shape to get familiar with the structure of the array
b.shape

(2,)